# Q1. 建立一個包含以下水果庫存的 Series：`Apple: 20`, `Banana: 40`, `Cherry: 15`。
2. 進貨了！將 `Apple` 的數量增加 10。
3. 使用**布林篩選 (Boolean Indexing)** 找出所有大於 20 的數值。
4. 把 `Cherry` 從清單中刪除。
5. 輸出最後的庫存清單。

In [11]:
import pandas as pd

# 1. 建立 Series
inventory = pd.Series({'Apple': 20, 'Banana': 40, 'Cherry': 15})
print(inventory, '\n')

# 2. 更新 Apple 數量
inventory['Apple'] += 10
print('inventory["Apple"] += 10\n', inventory, '\n')


# 3. 使用**布林篩選 (Boolean Indexing)** 找出所有大於 20 的數值。
print('庫存清單 > 20 :\n', inventory[inventory>20], '\n')

# 4. 刪除 Cherry (使用 drop)
inventory = inventory.drop('Cherry')

print("更新後的庫存清單：")
print(inventory)

Apple     20
Banana    40
Cherry    15
dtype: int64

inventory["Apple"] += 10
 Apple     30
Banana    40
Cherry    15
dtype: int64

庫存清單 > 20 :
 Apple     30
Banana    40
dtype: int64

更新後的庫存清單：
Apple     30
Banana    40
dtype: int64

---
# Q2 : 給定以下 DataFrame 請完成以下操作：
* 使用 loc 選出 A > B 的
* 再使用 iloc 取出結果中的 前 3 只輸出欄位 ["A", "C"]

In [2]:
import pandas as pd
df = pd.DataFrame({"A": [5, 12, 8, 20, 15],
                   "B": [7, 9, 10, 3, 6],
                   "C": [2, 4, 6, 8, 10]}, index=["r1", "r2", "r3", "r4", "r5"])
print(df, '\n')
step1 = df.loc[df["A"] > df["B"]];    print(step1, '\n')
result = step1.iloc[:3, [0, 2]];  print(result, '\n')
result = step1.iloc[:3, ::2];  print(result, '\n')

     A   B   C
r1   5   7   2
r2  12   9   4
r3   8  10   6
r4  20   3   8
r5  15   6  10

     A  B   C
r2  12  9   4
r4  20  3   8
r5  15  6  10

     A   C
r2  12   4
r4  20   8
r5  15  10

     A   C
r2  12   4
r4  20   8
r5  15  10

---
# Q3 準備一個簡單的範例 DataFrame：

# 建立基礎資料

```python

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [25, 30, 35, 40, 45],
    'City': ['Taipei', 'London', 'New York', 'Tokyo', 'Paris']
}
df = pd.DataFrame(data, index=['ID1', 'ID2', 'ID3', 'ID4', 'ID5'])

1. 使用 `loc` 提取索引標籤為 `ID2` 的那一行資料。
2. 使用 `iloc` 提取最後一行（Eve）的資料。
3. 使用 `loc` 同時取得 `ID3` 的 `Name` 欄位數值。

In [3]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [25, 30, 35, 40, 45],
    'City': ['Taipei', 'London', 'New York', 'Tokyo', 'Paris']
}
df = pd.DataFrame(data, index=['ID1', 'ID2', 'ID3', 'ID4', 'ID5'])
df

        Name  Age      City
ID1    Alice   25    Taipei
ID2      Bob   30    London
ID3  Charlie   35  New York
ID4    David   40     Tokyo
ID5      Eve   45     Paris

In [ ]:
# 1. 使用 loc 提取索引標籤為 ID2 的那一行資料
row_id2 = df.loc['ID2']

# 2. 使用 iloc 提取最後一行（Eve）的資料
last_row = df.iloc[-1]

# 3. 使用 loc 同時取得 ID3 的 Name 欄位數值
charlie_name = df.loc['ID3', 'Name']

print(f"ID2 資料:\n{row_id2}\n")
print(f"最後一行資料: {last_row['Name']}")
print(f"ID3 的姓名: {charlie_name}")

# Q3-1
1. 使用 `iloc` 選取前 3 行資料。
2. 使用 `loc` 選取從 `ID2` 到 `ID4` 的所有資料（包含 ID4）。
3. **觀察：** 請注意 `loc` 與 `iloc` 在切片「終點」包含性上的差異。

In [ ]:
# 1. 使用 iloc 選取前 3 行資料。
first_three_iloc = df.iloc[0:3]

# 2. 使用 loc 選取從 ID2 到 ID4 的所有資料（包含 ID4）
middle_rows_loc = df.loc['ID2':'ID4']

print("iloc 前三行（位置 0, 1, 2）：")
print(first_three_iloc)
print("\nloc 從 ID2 到 ID4（包含 ID4）：")
print(middle_rows_loc)

---
# Q4 特徵與標籤 (X, y) 分離分割

在實務上，我們通常會先將 DataFrame 分成 **X (特徵)** 與 **y (目標)**。

1. 從 DataFrame 中提取 `Target` 欄位作為 `y`，其餘欄位作為 `X`。
2. 將 `X` 與 `y` 同時進行分割，測試集佔 **30%**。
3. 輸出 `X_train` 與 `X_test` 的形狀 (shape)。

In [4]:
import pandas as pd
from sklearn.model_selection import train_test_split

data = {
    'Height': [170, 160, 180, 175, 150, 165, 190, 155],
    'Weight': [70, 55, 85, 75, 45, 60, 95, 50],
    'Target': [1, 0, 1, 1, 0, 0, 1, 0]
}
df = pd.DataFrame(data)
df

   Height  Weight  Target
0     170      70       1
1     160      55       0
2     180      85       1
3     175      75       1
4     150      45       0
5     165      60       0
6     190      95       1
7     155      50       0

In [ ]:
# 1. 從 DataFrame 中提取 Target 欄位作為 y，其餘欄位作為 X
X = df.drop('Target', axis=1)
y = df['Target']

# 2. 將 X 與 y 同時進行分割，測試集佔 30%。
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

# 3. 輸出 X_train 與 X_test 的形狀 (shape)。
print("X_train 的形狀:", X_train.shape)
print("X_test 的形狀:", X_test.shape)

X_train 的形狀: (5, 2)
X_test 的形狀: (3, 2)

---
# Q5 我們先建立一個簡單的銷售資料 DataFrame 作為練習背景：

```python
import pandas as pd
import numpy as np

data = {
    'Product': ['Apple', 'Banana', 'Orange', 'Apple', 'Banana', 'Grape', np.nan],
    'Sales': [100, 150, 200, 120, 150, 300, 50],
    'Inventory': [20, 35, 40, 15, 35, 10, 5]
}
df = pd.DataFrame(data)

1. 顯示該 DataFrame 的前 3 筆資料。
2. 使用一個函數輸出資料的欄位名稱、資料型別（dtypes）以及是否有缺失值（non-null counts）。
3. 取得該資料表的「形狀」（幾列幾欄）。
4. 針對數值欄位（Sales, Inventory），輸出快速統計摘要（包含平均值、標準差、最大最小值等）。
5. 計算 `Sales` 欄位的總和。
6. 找出 `Inventory` 欄位的平均值。

In [2]:
import pandas as pd
import numpy as np

data = {
    'Product': ['Apple', 'Banana', 'Orange', 'Apple', 'Banana', 'Grape', np.nan],
    'Sales': [100, 150, 200, 120, 150, 300, 50],
    'Inventory': [20, 35, 40, 15, 35, 10, 5]
}
df = pd.DataFrame(data)
df

  Product  Sales  Inventory
0   Apple    100         20
1  Banana    150         35
2  Orange    200         40
3   Apple    120         15
4  Banana    150         35
5   Grape    300         10
6     NaN     50          5

In [4]:
# 1. 顯示該 DataFrame 的前 3 筆資料。
print("前 3 筆資料：")
print(df.head(3))

# 2. 使用 info 函數輸出資料的欄位名稱、資料型別（dtypes）以及是否有缺失值（non-null counts）
print("\n資料詳細資訊：")
df.info()

# 3. 取得該資料表的「形狀」（幾列幾欄）
print(f"\n資料形狀: {df.shape}")

# 4. 針對數值欄位（Sales, Inventory），輸出 describe 快速統計摘要（包含平均值、標準差、最大最小值等）
print("\n數值統計摘要：")
print(df.describe())

# 5. 計算 Sales 總和
total_sales = df['Sales'].sum()

# 6. 計算 Inventory 平均值
avg_inventory = df['Inventory'].mean()

print(f"\n總銷售額: {total_sales}")
print(f"平均庫存: {avg_inventory:.2f}")

前 3 筆資料：
  Product  Sales  Inventory
0   Apple    100         20
1  Banana    150         35
2  Orange    200         40

資料詳細資訊：
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Product    6 non-null      object
 1   Sales      7 non-null      int64
 2   Inventory  7 non-null      int64
dtypes: int64(2), object(1)
memory usage: 296.0+ bytes

資料形狀: (7, 3)

數值統計摘要：
            Sales  Inventory
count    7.000000   7.000000
mean   152.857143  22.857143
std     79.940454  13.801311
min     50.000000   5.000000
25%    110.000000  12.500000
50%    150.000000  20.000000
75%    175.000000  35.000000
max    300.000000  40.000000

總銷售額: 1070
平均庫存: 22.86

---
# Q6 我們先建立一個「資料」DataFrame 作為練習：

```python
import pandas as pd
import numpy as np

data = {
    'Order_ID': [101, 102, 102, 104, 105],
    'Price': ['100', '250', '250', np.nan, '150'],
    'Date': ['2026-01-01', '2026-01-02', '2026-01-02', '2026-01-04', '2026-01-05']
}
df = pd.DataFrame(data)
```
1. 檢查 DataFrame 中是否有重複的列（Rows）。
2. 刪除重複的資料，僅保留第一次出現的紀錄。
3. 確認刪除後的資料筆數。
4. 找出 `Price` 欄位中缺失值（NaN）的數量。
5. 使用該欄位的**平均值**或**固定數值（例如 0）**來填補缺失值。
6. **挑戰：** 確保填補後，該欄位不再有缺失值。

In [7]:
import pandas as pd
import numpy as np

data = {
    'Order_ID': [101, 102, 102, 104, 105],
    'Price': ['100', '250', '250', np.nan, '150'],
    'Date': ['2026-01-01', '2026-01-02', '2026-01-02', '2026-01-04', '2026-01-05']
}
df = pd.DataFrame(data)

data = {
    'Order_ID': [101, 102, 102, 104, 105],
    'Price': ['100', '250', '250', np.nan, '150'],
    'Date': ['2026-01-01', '2026-01-02', '2026-01-02', '2026-01-04', '2026-01-05']
}
df = pd.DataFrame(data)

# 1. 檢查重複值 (回傳 True/False)
print("是否有重複行 ：", df.duplicated().any())

# 2. 刪除重複資料 (inplace=True 會直接修改原始 df)
df = df.drop_duplicates()

# 3. 確認刪除後的資料筆數
print("\n刪除重複後的資料 ：")
print(df)

# 4. 檢查缺失值
print("\n填補前缺失值數量 ：")
print(df.isnull().sum())

# 5. 填補缺失值 (這裡示範填補 0)
# 注意：在處理數值計算前，填補是必要的
df['Price'] = df['Price'].fillna(0)

# 6. 確保填補後，該欄位不再有缺失值。
print("\n填補後缺失值數量 ： ", df['Price'].isnull().sum())

是否有重複行： True

刪除重複後的資料：
   Order_ID Price        Date
0       101   100  2026-01-01
1       102   250  2026-01-02
3       104   NaN  2026-01-04
4       105   150  2026-01-05

填補前缺失值數量：
Order_ID    0
Price       1
Date        0
dtype: int64

填補後缺失值數量：  0

---
# Q7 我們先建立一個簡單的銷售紀錄 DataFrame：

```python
import pandas as pd

data = {
    'Department': ['Electronics', 'Clothing', 'Electronics', 'Home', 'Clothing', 'Home'],
    'Employee': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank'],
    'Sales': [50000, 30000, 45000, 20000, 35000, 25000],
    'Region': ['North', 'South', 'North', 'South', 'North', 'South']
}
df = pd.DataFrame(data)

```
1. 根據 `Department`（部門）進行分組。
2. 計算每個部門的**總銷售額 (Sales)**。
3. 根據 `Department` 進行分組。
4. 同時計算每個部門銷售額的**平均值 (mean)**、**最大值 (max)** 以及**員工人數 (count)**。
5. **提示：** 使用 `.agg()` 函數。

In [8]:
import pandas as pd

data = {
    'Department': ['Electronics', 'Clothing', 'Electronics', 'Home', 'Clothing', 'Home'],
    'Employee': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank'],
    'Sales': [50000, 30000, 45000, 20000, 35000, 25000],
    'Region': ['North', 'South', 'North', 'South', 'North', 'South']
}
df = pd.DataFrame(data)

# 1. 根據 Department（部門）進行分組。
# 2. 計算每個部門的總銷售額 (Sales)。
dept_sales = df.groupby('Department')['Sales'].sum()

print("各部門總銷售額：")
print(dept_sales)

# 3. 根據 Department 進行分組。
# 4. 同時計算每個部門銷售額的平均值 (mean)、最大值 (max) 以及員工人數 (count)。
dept_stats = df.groupby('Department')['Sales'].agg(['mean', 'max', 'count'])

print("各部門詳細統計：")
print(dept_stats)

各部門總銷售額：
Department
Clothing       65000
Electronics    95000
Home           45000
Name: Sales, dtype: int64
各部門詳細統計：
                mean    max  count
Department
Clothing     32500.0  35000      2
Electronics  47500.0  50000      2
Home         22500.0  25000      2

---
# Q8 : 給定訂單資料, 請完成以下操作：

1. 將兩個日期欄位轉為 datetime
2. 計算每筆訂單的 **出貨天數（ship_date - order_date), 新增到欄位 `days_to_ship`
3. 只輸出 `days_to_ship > 3` 的資料

In [18]:
df = pd.DataFrame({"order_date": ["2024-06-01", "2024-06-04", "2024-06-10"],
                   "ship_date":  ["2024-06-03", "2024-06-05", "2024-06-15"]})

# 1. 將兩個日期欄位轉為 datetime
df["order_date"] = pd.to_datetime(df["order_date"]);    print(df, '\n')
df["ship_date"] = pd.to_datetime(df["ship_date"]);    print(df, '\n')

# 2. 計算每筆訂單的 出貨天數（ship_date - order_date, 新增到欄位 `days_to_ship`

df["days_to_ship"] = (df["ship_date"] - df["order_date"]).dt.days;    print(df, '\n')

# 3. 只輸出 `days_to_ship > 3` 的資料
result = df[df["days_to_ship"] > 3];    print(df, '\n')

  order_date   ship_date
0 2024-06-01  2024-06-03
1 2024-06-04  2024-06-05
2 2024-06-10  2024-06-15

  order_date  ship_date
0 2024-06-01 2024-06-03
1 2024-06-04 2024-06-05
2 2024-06-10 2024-06-15

  order_date  ship_date  days_to_ship
0 2024-06-01 2024-06-03             2
1 2024-06-04 2024-06-05             1
2 2024-06-10 2024-06-15             5

  order_date  ship_date  days_to_ship
0 2024-06-01 2024-06-03             2
1 2024-06-04 2024-06-05             1
2 2024-06-10 2024-06-15             5

---
# Q9 檔案的讀取與輸出

1. 將現有的 DataFrame 儲存為名為 `data.csv` 的檔案，且**不保留**索引（index）。
2. 重新讀取該 `data.csv` 檔案到一個新的變數 `df_new` 中。
3. 顯示 `df_new` 的前 5 筆資料。
4. 讀取 `data.csv` 時，指定只讀取 `Name` 這一個欄位（使用 `usecols` 參數）。
5. 在讀取過程中，直接將 `Name` 欄位設定為該 DataFrame 的索引（使用 `index_col` 參數）。
6. 將資料儲存為 Excel 格式（`output.xlsx`）。
```python
import pandas as pd

# 準備範例資料
df = pd.DataFrame({'Name': ['Alice', 'Bob', 'Charlie'], 'Score': [85, 90, 78]})

In [15]:
import pandas as pd

# 準備範例資料
df = pd.DataFrame({'Name': ['Alice', 'Bob', 'Charlie'], 'Score': [85, 90, 78]})
print(df)
# 1. 儲存為 CSV (index=False 是為了避免多出一欄未命名的索引欄)
df.to_csv('data.csv', index=False)

# 2. 重新讀取該 data.csv 檔案到一個新的變數 df_new 中
df_new = pd.read_csv('data.csv')

# 3. 顯示 df_new 的前 5 筆資料
print(f"\n讀取的5 筆資料內容：\n{df_new.head()}\n")

# 4. 讀取 data.csv 時，指定只讀取 Name 這一個欄位（使用 usecols 參數）
df_named = pd.read_csv('data.csv', index_col='Name')
print('\n使用 Name, index_col 參數\n', df_named, '\n')

# 5. 在讀取過程中，直接將 Name 欄位設定為該 DataFrame 的索引（使用 index_col 參數）
df_named_idx = pd.read_csv('data.csv', usecols=['Name'])
print("\n以 Name usecols 的 DataFrame：\n", df_named_idx, '\n')

# 6. 將資料儲存為 Excel 格式（output.xlsx）
df.to_excel('output.xlsx', sheet_name='Sales', index=False)

print("\nExcel 檔案 'output.xlsx' 已建立，包含 Sales 與 Inventory 兩個工作表。")

      Name  Score
0    Alice     85
1      Bob     90
2  Charlie     78

讀取的5 筆資料內容：
      Name  Score
0    Alice     85
1      Bob     90
2  Charlie     78


使用 Name, index_col 參數
          Score
Name
Alice       85
Bob         90
Charlie     78


以 Name usecols 的 DataFrame：
       Name
0    Alice
1      Bob
2  Charlie


Excel 檔案 'output.xlsx' 已建立，包含 Sales 與 Inventory 兩個工作表。

---
# Q10  Data Wrangling 中最核心的「資料組合」動作，

你有兩張表，一張是「員工姓名表」，另一張是「員工部門表」。

1. 建立兩個 DataFrame：
* `df_names`: 包含 `ID` (1, 2, 3) 與 `Name` (Alice, Bob, Charlie)。
* `df_depts`: 包含 `ID` (2, 3, 4) 與 `Dept` (HR, IT, Sales)。

```python
import pandas as pd

# 1. 準備資料
df_names = pd.DataFrame({'ID': [1, 2, 3], 'Name': ['Alice', 'Bob', 'Charlie']})
df_depts = pd.DataFrame({'ID': [2, 3, 4], 'Dept': ['HR', 'IT', 'Sales']})
```
2. 使用 **Inner Join**（內連接）合併這兩張表。
3. 使用 **Left Join**（左連接）合併這兩張表，並觀察結果。
4. 將這兩個 DataFrame 垂直合併成一整年的清單。
5. **要求：** 合併後要重新重置索引（index），避免出現重複的 0, 1。

In [19]:
import pandas as pd

# 1. 準備資料
df_names = pd.DataFrame({'ID': [1, 2, 3], 'Name': ['Alice', 'Bob', 'Charlie']})
df_depts = pd.DataFrame({'ID': [2, 3, 4], 'Dept': ['HR', 'IT', 'Sales']})

# 2. Inner Join (只保留 ID 相同的交集：2, 3)
inner_result = pd.merge(df_names, df_depts, on='ID', how='inner')

# 3. Left Join (保留左表所有 ID，右表無對應則補 NaN)
left_result = pd.merge(df_names, df_depts, on='ID', how='left')

print("Inner Join 結果：\n", inner_result)
print("\nLeft Join 結果：\n", left_result)

# 4 & 5 垂直合併並重置索引
# ignore_index=True 會捨棄原本的索引並生成 0, 1, 2, 3...
# df_comb = pd.concat([df_names, df_depts], ignore_index=True)
df_comb = pd.merge(df_names, df_depts, on='ID', how='outer')
print(f"\n合併後的年度清單：\n{df_comb}")

Inner Join 結果：
    ID     Name Dept
0   2      Bob   HR
1   3  Charlie   IT

Left Join 結果：
    ID     Name Dept
0   1    Alice  NaN
1   2      Bob   HR
2   3  Charlie   IT

合併後的年度清單：
   ID     Name   Dept
0   1    Alice    NaN
1   2      Bob     HR
2   3  Charlie     IT
3   4      NaN  Sales

In [7]:
import pandas as pd

# 1. 準備資料
df_names = pd.DataFrame({'ID': [1, 2, 3], 'Name': ['Alice', 'Bob', 'Charlie']})
df_depts = pd.DataFrame({'ID': [2, 3, 4], 'Dept': ['HR', 'IT', 'Sales']})
print(df_names, '\n\n', df_depts, '\n')
# 2. Inner Join (只保留 ID 相同的交集：2, 3)
inner_result = pd.merge(df_names, df_depts, on='ID', how='inner')
# print('ddd', pd.concat([df_names, df_depts], axis=1, join='inner'))
# 3. Left Join (保留左表所有 ID，右表無對應則補 NaN)
left_result = pd.merge(df_names, df_depts, on='ID', how='left')

print("Inner Join 結果：\n", inner_result)
print("\nLeft Join 結果：\n", left_result)

# 4 & 5 垂直合併並重置索引
# ignore_index=True 會捨棄原本的索引並生成 0, 1, 2, 3...
df_comb = pd.concat([df_names, df_depts], ignore_index=True)

print("\n合併後的年度清單：")
print(df_comb)

   ID     Name
0   1    Alice
1   2      Bob
2   3  Charlie

    ID   Dept
0   2     HR
1   3     IT
2   4  Sales

Inner Join 結果：
    ID     Name Dept
0   2      Bob   HR
1   3  Charlie   IT

Left Join 結果：
    ID     Name Dept
0   1    Alice  NaN
1   2      Bob   HR
2   3  Charlie   IT

合併後的年度清單：
   ID     Name   Dept
0   1    Alice    NaN
1   2      Bob    NaN
2   3  Charlie    NaN
3   2      NaN     HR
4   3      NaN     IT
5   4      NaN  Sales